# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.

name: 'Login using the Service Principal user'

on: [ push, pull_request, workflow_dispatch ]


env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ROOT_PATH: '${{github.workspace}}/terraform-src'
  NUMBER_OF_CONCURRENT_THREADS: 5
  KEY_VAULT_NAME: 'formuleeinsvault'
  LOCATION: 'WestEurope'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Key-vault using azure cli script
        uses: azure/powershell@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            $resources = az resource list --resource-group myResourceGroup | ConvertFrom-Json

            foreach ($resource in $resources) {
                az resource delete --resource-group myResourceGroup --ids $resource.id --verbose
            }
